config/routes.rb
Rails.application.routes.draw do
  root to: "flights#index"
  resources :pnrs
  resources :bookings
  resources :flights
  resources :seat_maps
  resources :flight_configs
  get 'user/index'
  get 'user/show'
  get 'user/delete'
  devise_for :users
end

app/models/pnr.rb
class Pnr < ApplicationRecord
  belongs_to :booking
  belongs_to :flight

  validates_presence_of :seat_class, :booking_id, :flight_id
end

app/controllers/pnrs_controller.rb
class PnrsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_pnr, only: [:show, :edit, :update, :destroy]

  def index
    @pnrs = Pnr.all
  end

  def show
  end

  def new
    if current_user && current_user.is_admin
      @pnr = Pnr.new
    else
      redirect_to pnrs_url, notice: "Sorry, you don't have the rights"
    end
  end

  def edit
  end

  def create
    @pnr = Pnr.new(pnr_params)

    respond_to do |format|
      if @pnr.save
        format.html { redirect_to @pnr, notice: 'Pnr was successfully created.' }
        format.json { render :show, status: :created, location: @pnr }
      else
        format.html { render :new }
        format.json { render json: @pnr.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pnr.update(pnr_params)
        format.html { redirect_to @pnr, notice: 'Pnr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pnr }
      else
        format.html { render :edit }
        format.json { render json: @pnr.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pnr.destroy
    respond_to do |format|
      format.html { redirect_to pnrs_url, notice: 'Pnr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_pnr
      @pnr = Pnr.find(params[:id])
    end

    def pnr_params
      params.require(:pnr).permit(:seat_class, :booking_id, :flight_id)
    end
end

app/helpers/pnrs_helper.rb
module PnrsHelper
end

app/views/pnrs/_form.html.erb
<%= simple_form_for(@pnr) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :seat_class %>
    <%= f.association :booking %>
    <%= f.association :flight %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pnrs/edit.html.erb
<h1>Editing Pnr</h1>

<%= render 'form', pnr: @pnr %>

<%= link_to 'Show', @pnr %> |
<%= link_to 'Back', pnrs_path %>

app/views/pnrs/index.html.erb
<h1>Pnrs</h1>

<table>
  <thead>
    <tr>
      <th>Seat class</th>
      <th>Booking</th>
      <th>Flight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pnrs.each do |pnr| %>
      <tr>
        <td><%= pnr.seat_class %></td>
        <td><%= pnr.booking_id %></td>
        <td><%= pnr.flight_id %></td>
        <td><%= link_to 'Show', pnr %></td>
        <% if current_user && current_user.is_admin %>
          <div>
            <td><%= link_to 'Edit', edit_pnr_path(pnr) %></td>
            <td><%= link_to 'Destroy', pnr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pnr', new_pnr_path %>

app/views/pnrs/new.html.erb
<h1>New Pnr</h1>

<%= render 'form', pnr: @pnr %>

<%= link_to 'Back', pnrs_path %>

app/views/pnrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seat class:</strong>
  <%= @pnr.seat_class %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @pnr.booking_id %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @pnr.flight_id %>
</p>

<%= link_to 'Edit', edit_pnr_path(@pnr) %> |
<%= link_to 'Back', pnrs_path %>