config/routes.rb
Rails.application.routes.draw do
  root to: "flights#index"
  resources :pnrs
  resources :bookings
  resources :flights
  resources :seat_maps
  resources :flight_configs
  get 'user/index'
  get 'user/show'
  get 'user/delete'
  devise_for :users
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :flightConfig
  belongs_to :seatMap
  
  validates_presence_of :name, :origin, :destination, :seatMap_id, :flightConfig_id, :seatMap_id
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def index
    @flights = Flight.all
  end

  def show
  end

  def new
    if current_user && current_user.is_admin
      @flight = Flight.new
    else
      redirect_to flights_url, notice: "Sorry, you don't have the rights"
    end
  end

  def edit
  end

  def create
    @flight = Flight.new(flight_params)
    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_flight
      @flight = Flight.find(params[:id])
    end

    def flight_params
      params.require(:flight).permit(:name, :origin, :destination, :flightConfig_id, :seatMap_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= simple_form_for(@flight) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :origin %>
    <%= f.input :destination %>
    <%= f.association :flightConfig %>
    <%= f.association :seatMap %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Flightconfig</th>
      <th>Seatmap</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.flightConfig_id %></td>
        <td><%= flight.seatMap_id %></td>
        <td><%= link_to 'Show', flight %></td>
        <% if current_user && current_user.is_admin %>
          <div>
            <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
            <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flight.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Flightconfig:</strong>
  <%= @flight.flightConfig_id %>
</p>

<p>
  <strong>Seatmap:</strong>
  <%= @flight.seatMap_id %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>