config/routes.rb
Rails.application.routes.draw do
  root to: "flights#index"
  resources :pnrs
  resources :bookings
  resources :flights
  resources :seat_maps
  resources :flight_configs
  get 'user/index'
  get 'user/show'
  get 'user/delete'
  devise_for :users
end

app/models/flight_config.rb
class FlightConfig < ApplicationRecord
  validates_presence_of :flight_origin, :flight_destination, :arrival_time, :departure_time, :economy_class_price
end

app/controllers/flight_configs_controller.rb
class FlightConfigsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_flight_config, only: [:show, :edit, :update, :destroy]

  def name
    @flight_config.flight_origin[0..2] + @flight_config.flight_destination[0..2]
  end

  def index
    @flight_configs = FlightConfig.all
  end

  def show
  end

  def new
    if current_user && current_user.is_admin
      @flight_config = FlightConfig.new
    else
      redirect_to flight_configs_url, notice: "Sorry, you don't have the rights"
    end
  end

  def edit
  end

  def create
    @flight_config = FlightConfig.new(flight_config_params)

    respond_to do |format|
      if @flight_config.save
        format.html { redirect_to @flight_config, notice: 'Flight config was successfully created.' }
        format.json { render :show, status: :created, location: @flight_config }
      else
        format.html { render :new }
        format.json { render json: @flight_config.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight_config.update(flight_config_params)
        format.html { redirect_to @flight_config, notice: 'Flight config was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight_config }
      else
        format.html { render :edit }
        format.json { render json: @flight_config.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flight_config.destroy
    respond_to do |format|
      format.html { redirect_to flight_configs_url, notice: 'Flight config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_flight_config
      @flight_config = FlightConfig.find(params[:id])
    end

    def flight_config_params
      params.require(:flight_config).permit(:flight_origin, :flight_destination, :arrival_time, :departure_time, :first_class_price, :business_class_price, :economy_class_price)
    end
end

app/helpers/flight_configs_helper.rb
module FlightConfigsHelper
end

app/views/flight_configs/_form.html.erb
<%= simple_form_for(@flight_config) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :flight_origin %>
    <%= f.input :flight_destination %>
    <%= f.input :arrival_time %>
    <%= f.input :departure_time %>
    <%= f.input :first_class_price %>
    <%= f.input :business_class_price %>
    <%= f.input :economy_class_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flight_configs/edit.html.erb
<h1>Editing Flight Config</h1>

<%= render 'form', flight_config: @flight_config %>

<%= link_to 'Show', @flight_config %> |
<%= link_to 'Back', flight_configs_path %>

app/views/flight_configs/index.html.erb
<h1>Flight Configs</h1>

<table>
  <thead>
    <tr>
      <th>Flight origin</th>
      <th>Flight destination</th>
      <th>Arrival time</th>
      <th>Departure time</th>
      <th>First class price</th>
      <th>Business class price</th>
      <th>Economy class price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_configs.each do |flight_config| %>
      <tr>
        <td class="p-2 m-1"><%= flight_config.flight_origin %></td>
        <td class="p-2 m-1"><%= flight_config.flight_destination %></td>
        <td class="p-3 m-1"><%= flight_config.arrival_time %></td>
        <td class="p-3 m-1"><%= flight_config.departure_time %></td>
        <td class="p-2 m-1"><%= flight_config.first_class_price || "NA" %></td>
        <td class="p-2 m-1"><%= flight_config.business_class_price || "NA" %></td>
        <td class="p-2 m-1"><%= flight_config.economy_class_price || "NA" %></td>
        <td class="p-2 m-1"><%= link_to 'Show', flight_config %></td>
        <% if current_user && current_user.is_admin %>
          <div>
            <td class="p-2 m-1"><%= link_to 'Edit', edit_flight_config_path(flight_config) %></td>
            <td class="p-2 m-1"><%= link_to 'Destroy', flight_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight Config', new_flight_config_path %>

app/views/flight_configs/new.html.erb
<h1>New Flight Config</h1>

<%= render 'form', flight_config: @flight_config %>

<%= link_to 'Back', flight_configs_path %>

app/views/flight_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight origin:</strong>
  <%= @flight_config.flight_origin %>
</p>

<p>
  <strong>Flight destination:</strong>
  <%= @flight_config.flight_destination %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @flight_config.arrival_time %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @flight_config.departure_time %>
</p>

<p>
  <strong>First class price:</strong>
  <%= @flight_config.first_class_price %>
</p>

<p>
  <strong>Business class price:</strong>
  <%= @flight_config.business_class_price %>
</p>

<p>
  <strong>Economy class price:</strong>
  <%= @flight_config.economy_class_price %>
</p>

<%= link_to 'Edit', edit_flight_config_path(@flight_config) %> |
<%= link_to 'Back', flight_configs_path %>