config/routes.rb
Rails.application.routes.draw do
  root to: "flights#index"
  resources :pnrs
  resources :bookings
  resources :flights
  resources :seat_maps
  resources :flight_configs
  get 'user/index'
  get 'user/show'
  get 'user/delete'
  devise_for :users
end

app/views/layouts/_alerts.html.erb
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="text-center p-2 mt-5">  -- Developed by <a href="https://www.linkedin.com/in/thebhushanmhatre" target="_blank">Bhushan Mhatre </a> --  </div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <a class="navbar-brand" href="/"><h2>BookFlights</h2></a>
  
  <%= link_to "FlightConfigs", flight_configs_path, :class => "nav-link" %>
  <%= link_to "FlightPath", flights_path, :class => "nav-link" %>
  <%= link_to "SeatMap", seat_maps_path, :class => "nav-link" %>
  
  <% if current_user && current_user.is_admin %>
    <%= link_to "Booking", bookings_path, :class => "nav-link" %>
    <%= link_to "PNR", pnrs_path, :class => "nav-link" %>
    <%= link_to "Users", user_index_path, :class => "nav-link" %>
  <% end %>

  <% if current_user %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link" %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => "nav-link" %>
    <%= link_to "Log In", new_user_session_path, :class => "nav-link" %>
  <% end %>
</div>

<% if current_user && current_user.is_admin %>
  <div class="well bg-info p-2 mt-1">
    <h3>Admin Panel</h3>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookFlights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container bg-light">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>